<?php
$categoryUrl = $block->getBlogCategoryUrl();
$category    = $block->getBlogCategoryFromUrl($categoryUrl);
$articles    = $block->getLatestPosts(3, $category->getId());
?>
<h2>Articles</h2>
<?php
if ($articles->getSize()> 0) { ?>
    <div class="blog-article-list-box">
        <?php foreach ($articles as $article) { ?>
            <div class="blog-article-row">
                <a href="/blog/<?php echo $category->getUrl() . '/' . $article->getUrl(); ?>" title="<?php echo $article->getTitle(); ?>" class="article-name">
                    <?php echo $article->getTitle(); ?>
                </a>
                <div class="content">
                    <?php echo substr(strip_tags($article->getContent()), 0, 100); ?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>